thecut/portfolio/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from .feeds import LatestProjectFeed
from .views import client, project
from django.conf.urls import include, url

urls = [

    url(r'^clients/$',
        client.ListView.as_view(), name='client_list'),
    url(r'^clients/(?P<page>\d+)$',
        client.ListView.as_view(), name='paginated_client_list'),
    url(r'^clients/(?P<slug>[\w-]+)/$',
        client.DetailView.as_view(), name='client_detail'),

    # url(r'^clients/(?P<client_slug>[\w-]+)/projects/$',
    #     project.ListView.as_view(), name='client_project_list'),
    # url(r'^clients/(?P<client_slug>[\w-]+)/projects/(?P<page>\d+)$',
    #     project.ListView.as_view(), name='paginated_client_project_list'),

    url(r'^projects/$',
        project.ListView.as_view(), name='project_list'),
    url(r'^projects/(?P<page>\d+)$',
        project.ListView.as_view(), name='paginated_project_list'),
    url(r'^projects/(?P<slug>[\w-]+)/$',
        project.DetailView.as_view(), name='project_detail'),

    url(r'^projects/latest\.xml$', LatestProjectFeed(), name='project_feed'),

]

urlpatterns = [
    url(r'^', include(urls, namespace='portfolio')),
]

thecut/portfolio/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from thecut.ordering.models import OrderMixin
from thecut.publishing.models import SiteContentWithSlug
from thecut.publishing.utils import generate_unique_slug


class AbstractClient(OrderMixin, SiteContentWithSlug):

    link = models.URLField(blank=True, default='')
    logo = models.ImageField(
        upload_to='uploads/portfolio/clients/logos',
        blank=True, null=True)

    class Meta(OrderMixin.Meta, SiteContentWithSlug.Meta):
        abstract = True


class Client(AbstractClient):

    class Meta(AbstractClient.Meta):
        pass

    def get_absolute_url(self):
        return reverse('portfolio:client_detail', kwargs={'slug': self.slug})


class AbstractProject(OrderMixin, SiteContentWithSlug):

    link = models.URLField(blank=True, default='')

    class Meta(OrderMixin.Meta, SiteContentWithSlug.Meta):
        abstract = True


class Project(AbstractProject):

    """A client project or case-study."""

    client = models.ForeignKey('portfolio.Client', related_name='projects')

    class Meta(AbstractProject.Meta):
        pass

    def get_absolute_url(self):
        return reverse('portfolio:project_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        try:
            self.client
        except ObjectDoesNotExist:
            pass
        else:
            if not self.slug:
                queryset = self.__class__.objects.filter(site=self.site)
                slug = '{0}-{1}'.format(self.client, self)
                self.slug = generate_unique_slug(slug, queryset)
        return super(Project, self).save(*args, **kwargs)

thecut/portfolio/views/client.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from distutils.version import StrictVersion
from django import get_version
from django.shortcuts import redirect
from django.views import generic
from thecut.portfolio import settings
from thecut.portfolio.models import Client


class DetailView(generic.DetailView):

    context_object_name = 'client'
    model = Client
    template_name_field = 'template'

    def get_queryset(self, *args, **kwargs):
        queryset = super(DetailView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()


class ListView(generic.ListView):

    context_object_name = 'client_list'
    model = Client
    paginate_by = settings.CLIENT_PAGINATE_BY

    def get(self, *args, **kwargs):
        page = self.kwargs.get('page', None)
        if page is not None and int(page) < 2:
            return redirect('portfolio:client_list', permanent=True)
        return super(ListView, self).get(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        queryset = super(ListView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()

thecut/portfolio/views/project.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from distutils.version import StrictVersion
from django import get_version
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from thecut.portfolio import settings
from thecut.portfolio.models import Client, Project



class DetailView(generic.DetailView):

    context_object_name = 'project'
    model = Project
    template_name_field = 'template'

    def get_queryset(self, *args, **kwargs):
        queryset = super(DetailView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()


class ListView(generic.ListView):

    context_object_name = 'project_list'
    model = Project
    paginate_by = settings.PROJECT_PAGINATE_BY

    def get(self, *args, **kwargs):
        page = self.kwargs.get('page', None)
        if page is not None and int(page) < 2:
            client = self.get_client()
            if client:
                return redirect('portfolio:client_project_list',
                                slug=client.slug, permanent=True)
            else:
                return redirect('portfolio:project_list', permanent=True)
        return super(ListView, self).get(*args, **kwargs)

    def get_client(self):
        if not hasattr(self, '_client'):
            slug = self.kwargs.get('client_slug', None)
            if slug is not None:
                client = get_object_or_404(
                    Client.objects.current_site().active(), slug=slug)
            else:
                client = None
            self._client = client
        return self._client

    def get_context_data(self, *args, **kwargs):
        context_data = super(ListView, self).get_context_data(*args, **kwargs)
        context_data.setdefault('client', self.get_client())
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super(ListView, self).get_queryset(*args, **kwargs)
        client = self.get_client()
        if client:
            queryset = queryset.filter(client=client)
        return queryset.current_site().active()

thecut/portfolio/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% block extrahead %}{% endblock %}
  </head>
  
  <body>
    {% block content %}
    {% endblock %}
  </body>
  
</html>

thecut/portfolio/templates/portfolio/base.html
{% extends "base.html" %}

thecut/portfolio/templates/portfolio/client_detail.html
{% extends "portfolio/base.html" %}

{% block title %}{{ client.title }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if not client.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% if client.meta_description %}<meta name="description" content="{{ client.meta_description }}" />{% endif %}
{% endblock %}

{% block content %}

  <h1>{{ client.heading }}</h1>

  {% if client.featured_content %}<div>{{ client.featured_content }}</div>{% endif %}
  {% if client.content %}<div>{{ client.content|safe }}</div>{% endif %}

  <h2>Projects</h2>
  {% for project in client.projects.current_site.active %}
    {% if forloop.first %}<ul>{% endif %}
    <li>
      <a href="{{ project.get_absolute_url }}">
        {% if project.media.get_image %}<img src="{{ project.media.get_image }}" alt="{{ project }}" />{% endif %}
        {{ project }}
        {{ project.summary }}
      </a>
    </li>
    {% if forloop.last %}</ul>{% endif %}
  {% empty %}
    <p>No projects to display.</p>
  {% endfor %}

{% endblock %}

thecut/portfolio/templates/portfolio/client_list.html
{% extends "portfolio/base.html" %}

{% block title %}Clients - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}

  {% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}<link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "portfolio:client_list" %}{% else %}{% url "portfolio:paginated_client_list" page=page_obj.previous_page_number %}{% endif %}" />{% endif %}
    {% if page_obj.has_next %}<link rel="next" href="{% url "portfolio:paginated_client_list" page=page_obj.next_page_number %}" />{% endif %}
  {% endif %}

{% endblock %}

{% block content %}

  <h1>Clients</h1>

  {% for client in client_list %}
    {% if forloop.first %}<ul>{% endif %}
    <li>
      <a href="{{ client.get_absolute_url }}">
        {% if client.logo %}<img src="{{ client.logo.url }}" alt="{{ client }}" />{% endif %}
        {{ client }}
        {{ client.summary }}
      </a>
    </li>
    {% if forloop.last %}</ul>{% endif %}
  {% empty %}
    <p>No clients to display.</p>
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
  <div>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    {% if page_obj.has_previous %}<a href="{% if page_obj.previous_page_number == 1 %}{% url "portfolio:client_list" %}{% else %}{% url "portfolio:paginated_client_list" page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>{% endif %}
    {% if page_obj.has_next %}<a href="{% url "portfolio:paginated_client_list" page_obj.next_page_number %}" rel="next">next</a>{% endif %}
  </div>
  {% endif %}

{% endblock %}

thecut/portfolio/templates/portfolio/project_detail.html
{% extends "portfolio/base.html" %}
{% load thumbnail %}

{% block title %}{{ project.title }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if not project.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% if project.meta_description %}<meta name="description" content="{{ project.meta_description }}" />{% endif %}
{% endblock %}

{% block content %}

  <h1>{{ project.heading }}</h1>

  {% if project.featured_content %}<div>{{ project.featured_content }}</div>{% endif %}
  {% if project.content %}<div>{{ project.content|safe }}</div>{% endif %}

  {% spaceless %}{% for image in project.media.images %}
    {% if forloop.first %}<h2>Images</h2><ul>{% endif %}
    {% thumbnail image.get_image "200x200" as thumb %}
    <li><a href="{{ image.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ image }}" /></a></li>
    {% endthumbnail %}
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}{% endspaceless %}

  {% spaceless %}{% for document in project.media.documents %}
    {% if forloop.first %}<h2>Documents</h2><ul>{% endif %}
    {% thumbnail document.get_image "200x200" as thumb %}
    <li><a href="{{ document.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ document }}" /></a></li>
    {% endthumbnail %}
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}{% endspaceless %}

{% endblock %}

thecut/portfolio/templates/portfolio/project_list.html
{% extends "portfolio/base.html" %}

{% block title %}{% if client %}{{ client }} - {% endif %}Projects - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}

  {% if client %}
    {% if not client.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% else %}
    <link rel="alternate" href="{% url "portfolio:project_feed" %}" type="application/atom+xml" title="Latest Projects" />
  {% endif %}

  {% if page_obj.paginator.num_pages > 1 %}{% spaceless %}
    {% if page_obj.has_previous %}
      {% if client %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "portfolio:client_project_list" client_slug=client.slug %}{% else %}{% url "portfolio:paginated_client_project_list" client_slug=client.slug page=page_obj.previous_page_number %}{% endif %}" />
      {% else %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "portfolio:project_list" %}{% else %}{% url "portfolio:paginated_project_list" page=page_obj.previous_page_number %}{% endif %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      {% if client %}
        <link rel="next" href="{% url "portfolio:paginated_client_project_list" client_slug=client.slug page=page_obj.next_page_number %}" />
      {% else %}
        <link rel="next" href="{% url "portfolio:paginated_project_list" page=page_obj.next_page_number %}" />
      {% endif %}
    {% endif %}
  {% endspaceless %}{% endif %}
{% endblock %}

{% block content %}

  <h1>{% if client %}{{ client }} {% endif %}Projects</h1>

  {% for project in project_list %}
    {% if forloop.first %}<ul>{% endif %}
    <li>
      <a href="{{ project.get_absolute_url }}">
        {% if project.media.get_image %}<img src="{{ project.media.get_image }}" alt="{{ project }}" />{% endif %}
        {{ project }}
        {{ project.summary }}
      </a>
    </li>
    {% if forloop.last %}</ul>{% endif %}
  {% empty %}
    <p>No projects to display.</p>
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
  <div>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

    {% if page_obj.has_previous %}
      {% if client %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "portfolio:client_project_list" client_slug=client.slug %}{% else %}{% url "portfolio:paginated_client_project_list" client_slug=client.slug page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% else %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "portfolio:project_list" %}{% else %}{% url "portfolio:paginated_project_list" page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% endif %}
    {% endif %}

    {% if page_obj.has_next %}
      {% if client %}
        <a href="{% url "portfolio:paginated_client_project_list" client_slug=client.slug page=page_obj.next_page_number %}" rel="next">next</a>
      {% else %}
        <a href="{% url "portfolio:paginated_project_list" page=page_obj.next_page_number %}" rel="next">next</a>
      {% endif %}
    {% endif %}

  </div>
  {% endif %}

{% endblock %}